sudo: false

language: node_js

node_js:
  - '10.5'

matrix:
  include:
    - node_js: '10'
      env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
  include:
    - node_js: '11'
      env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"
  allow_failures:
    - env: "NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly"

git:
  depth: 3

cache:
  directories:
    - node_modules
    - ~/.npm

script:
  - npm run test

after_success:
  - npm run coverage
