sudo: false

language: node_js

matrix:
  include:
    - node_js: "10"
    - name: "Node.js: nightly"
      node_js: "node"
      env:
        - NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly
    - name: "Node.js: canary"
      node_js: "node"
      env:
        - NODEJS_ORG_MIRROR=https://nodejs.org/download/v8-canary

  allow_failures:
    - node_js: "node"
      env:
        - NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly
    - node_js: "node"
      env:
        - NODEJS_ORG_MIRROR=https://nodejs.org/download/v8-canary

branches:
  only:
    - master

git:
  depth: 3

cache:
  directories:
    - node_modules
    - ~/.npm

script:
  - npm run test

after_success:
  - npm run coverage
